### ISSUE TITLE
Incorrect Java Logo and Missing Technology Logos

### ISSUE THREAD

**Issue by sshrey15** [fork-commit-merge/fork-commit-merge-web#174]
### Incorrect Java Logo and Missing Technology Logos

**Issue Description:**
I noticed that the website displays logos for various programming languages and technologies, but there are a couple of issues with the logos being incorrect or missing. This issue aims to address these discrepancies and ensure the website provides accurate representations of the technologies.

**Incorrect Java Logo:**
The Java logo displayed on the website is not the correct version. It's essential to update the Java logo to reflect the current official logo. This helps in maintaining the accuracy and professionalism of the website.

**Missing Technology Logos:**
Additionally, I've noticed that some technology logos are missing from the website. It would be great to include logos for the missing technologies to ensure comprehensive coverage.

Suggested Actions:

Replace the incorrect Java logo with the up-to-date, official Java logo.
Add logos for the missing technology or programming languages to the website to provide complete and accurate information.

**Steps to Reproduce :**
```
Badges.tsx
IndexMain.tsx
badgesData.ts
```

**Screenshots :**
![issuse_logo](https://github.com/nikohoffren/fork-commit-merge-web/assets/126756634/4727eac4-b18f-4aed-9b66-4ba937775653)

**Comment by ruchikamuddinagiri** [comment]
Hi, can I also take this?

**Comment by nikohoffren** [comment]
> Hi, can I also take this?

Sure, go ahead!

**Comment by ruchikamuddinagiri** [comment]
Hi, as mentioned in my PR, I looked into the incorrect Java badge. It looks like we will have to put up with it for now since, as you know, we source our icons from the simple-icons collection and they do not have a Java logo available due to copyright issues.
Here are the relevant links - [https://github.com/simple-icons/simple-icons/pull/7378](https://github.com/simple-icons/simple-icons/pull/7378)

**Comment by nikohoffren** [comment]
> Hi, as mentioned in my PR, I looked into the incorrect Java badge. It looks like we will have to put up with it for now since, as you know, we source our icons from the simple-icons collection and they do not have a Java logo available due to copyright issues.
> Here are the relevant links - [https://github.com/simple-icons/simple-icons/pull/7378](https://github.com/simple-icons/simple-icons/pull/7378)

Oh okay, that's fine then. I'll close this issue for now and maybe later on in the future we can add some new/different icons if possible.
